server:
  port: 8761
eureka:
  instance:
    hostname: 12.12.43.253
  client:
    register-with-eureka: false #\u7531\u4E8E\u662F\u5355\u673A\uFF0C\u4E0D\u7528\u5C06\u672C\u670D\u52A1\u5668\u6CE8\u518C\u5230 Eureka \u670D\u52A1\u5668
    fetch-registry: false
    service-url:
      defaultZone: http://admin:123@12.12.43.253:8761/eureka
spring:
  security:
    basic:
      enable: true #\u4F7F\u7528\u7B80\u5355\u767B\u5F55\u6846
    user:
      name: admin
      password: 123
